In [ ]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [1]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.
##  there is a difference in the data type of variables 'list_' and 'array_list'.
## The'list_' variable is a Python list, which can contain elements of different data types. In this case, the elements are strings.
## The 'array_list' variable is a NumPy array, which has a fixed data type for all its elements. In this case, because
## all the elements in 'list_' are strings,  the data type of 'array_list' is also a string.

## To print the data types of both variables, you can use the 'type()' function:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [2]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
# To print the data type of each and every element of both the 'list_' and 'array_list' variables, you can use a loop and the 'type()' function:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# Q3. Considering the following changes in the variable, array_list:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

# To find the shape and size of the 'num_array' variable, you can use the '.shape' and '.size' attributes of NumPy arrays:

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

# To create a NumPy array of a 3x3 matrix containing only zeros, you can use the 'np.zeros()' function:

import numpy as np

# Create a 3x3 matrix of zeros
zeros_array = np.zeros((3, 3))

# Print the zeros_array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

# To create an identity matrix of shape '(5, 5)' using NumPy functions, you can use the 'np.identity()' function:

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the identity_matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
